# Open Kitty config remap.
map kitty_mod+f2 launch --tab-title="Kitty config" --cwd=~/.config/kitty nvim kitty.conf
# Open Neovim config.
map kitty_mod+f4 launch --tab-title="Neovim config" --cwd=~/.config/nvim nvim init.lua

# Create a new window splitting the space used by the existing one so that
# the two windows are placed one above the other.
map f5 launch --location=hsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side.
map f6 launch --location=vsplit

# Create a new window splitting the space used by the existing one so that
# the two windows are placed side by side if the existing window is wide or
# one above the other if the existing window is tall.
map f4 launch --location=split

# Rotate the current split, changing its split axis from vertical to
# horizontal or vice versa.
map f7 layout_action rotate

# Switch focus to the neighboring window in the indicated direction.
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

# Move the active window in the indicated direction.
map alt+shift+up move_window up
map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+down move_window down

# Set the bias of the split containing the currently focused window. The
# currently focused window will take up the specified percent of its parent
# window's size.
map alt+. layout_action bias 65
map alt+, layout_action bias 50

map ctrl+f1 set_window_title
# Moves the window into a new OS window.
map ctrl+f2 detach_window
# Moves the window into a new tab.
map ctrl+f3 detach_window new-tab
# Moves the tab into a new OS window.
map ctrl+f4 detach_tab
map f9 close_other_windows_in_tab

# I hack to solve a bug where scrolling binds stop working after a while.
# Might find a proper fix later.
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down
