# Open Kitty config remap.
map kitty_mod+f2 launch --type=tab --tab-title="Kitty config" --cwd=~/.config/kitty nvim kitty.conf
# Open Neovim config.
map kitty_mod+f4 launch --type=tab --tab-title="Neovim config" --cwd=~/.config/nvim nvim init.lua

# Will work in all enabled layouts (tall, fat, splits).
map f2 set_window_title
map f3 detach_window ask
map f4 launch --location=split
# Throws error in splits.
map f5 layout_action bias 50 66 75

# Does stuff only in splits.
map f6 launch --location=hsplit
map f7 launch --location=vsplit
map f8 layout_action rotate

# Will work in all enabled layouts (tall, fat, splits).
map f9 layout_action bias 50
map f10 close_other_windows_in_tab

# Switch focus to the neighboring window in the indicated direction.
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down

# Move the active window in the indicated direction.
map alt+shift+up move_window up
map alt+shift+left move_window left
map alt+shift+right move_window right
map alt+shift+down move_window down
