os_window_state maximized
new_tab PLG www
cd ~/Projects/pl/bonprix-www/
launch --title 'PLG cmdline'
cd ~/Projects/pl/bonprix-www/ssr/
launch --bias=66 --hold --title 'PLG ssr Neovim' --var window=plg_ssr_nvim nvim
focus_matching_window var:window=plg_ssr_nvim
cd ~/Projects/pl/bonprix-www/

new_tab FRG www
cd ~/Projects/fr/bonprix-www/
launch --title 'FRG cmdline'
cd ~/Projects/fr/bonprix-www/ssr/
launch --bias=66 --hold --title 'FRG ssr Neovim' --var window=frg_ssr_nvim nvim
focus_matching_window var:window=frg_ssr_nvim
cd ~/Projects/fr/bonprix-www/

new_tab Misc
cd ~
launch --hold neofetch
launch --bias=66 --var window=misc_dev
focus_matching_window var:window=misc_dev

new_os_window
os_window_state maximized
new_tab Connection server
cd ~/Projects/pl/bonprix-www/tools/
launch --title 'PLG connection'
cd ~/Projects/fr/bonprix-www/tools/
launch --location=hsplit --title 'FRG connection'

new_tab PLG www dev server
cd ~/Projects/pl/bonprix-www/tools/
launch

new_tab FRG www dev server
cd ~/Projects/fr/bonprix-www/tools/
launch

new_tab Btop
cd ~
launch --hold btop
