os_window_state maximized
new_tab Neovim
launch --hold neofetch

new_tab CmdLine
launch --hold neofetch

new_tab Misc
launch --hold neofetch
focus_tab 0

new_os_window
os_window_state maximized
layout splits
launch
launch --location=hsplit --bias=66
