os_window_state maximized
new_tab PLG www
cd ~/Projects/pl/bonprix-www/
launch
cd ~/Projects/pl/bonprix-www/ssr/
launch --location=vsplit --bias=64 --var window=plg_www nvim 
focus_matching_window var:window=plg_www

new_tab PLG cms
cd ~/Projects/pl/bonprix-cms/
launch
cd ~/Projects/pl/bonprix-cms/cms/
launch --location=vsplit --bias=64 --var window=plg_cms nvim 
focus_matching_window var:window=plg_cms

new_tab FRG www
cd ~/Projects/fr/bonprix-www/
launch
cd ~/Projects/fr/bonprix-www/ssr/
launch --location=vsplit --bias=64 --var window=frg_www nvim 
focus_matching_window var:window=frg_www

new_tab FRG cms
cd ~/Projects/fr/cms/
launch
cd ~/Projects/fr/cms/cms/
launch --location=vsplit --bias=64 --var window=frg_cms nvim 
focus_matching_window var:window=frg_cms

new_tab Misc
cd ~
launch --hold neofetch
launch --bias=64 --var window=misc
focus_matching_window var:window=misc

new_os_window
os_window_state maximized

new_tab PLG www
cd ~/Projects/pl/bonprix-www/tools/
launch
launch --location=hsplit --bias=66

new_tab PLG cms
cd ~/Projects/pl/bonprix-cms/tools/
launch
launch --location=hsplit --bias=66

new_tab FRG www
cd ~/Projects/fr/bonprix-www/tools/
launch
launch --location=hsplit --bias=66

new_tab FRG cms
cd ~/Projects/fr/cms/tools/
launch
launch --location=hsplit --bias=66
